// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhajouxbngysrtbcfxrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoYWpvdXhibmd5c3J0YmNmeHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzk4OTAsImV4cCI6MjA3Mjk1NTg5MH0.Y0UkADQ5-jAOiplVXb5xgujwBYjKe_rkT8WUkEkGNVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});